FROM python:3.11-slim

WORKDIR /app

COPY nuclei/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY nuclei/. .
COPY utils ./utils

# Download the onnx and TensorRT model weight
RUN pip install gdown
RUN mkdir -p /app/ckpts/nuclei-yolov8-colon
RUN gdown 1KD4jIj-DbKqahdX2fW-MhtZH06gRdVne -O /app/ckpts/nuclei-yolov8-colon/best.onnx


#RUN mkdir -p app/ckpts/nuclei-stardist/

#COPY nuclei/stardist_conic /app/ckpts/nuclei-stardist/stardist_conic
#COPY nuclei/stardist_model.onnx /app/ckpts/nuclei-stardist/best.onnx
#COPY nuclei/stardist2d.so .



# RUN export no_proxy="localhost"

CMD ["python", "app_consumer.py", "yolov8-colon"]
